[package]
name = "rustdo"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0"
ratatui = "0.29.0"
crossterm = "0.29.0"
